### ISSUE TITLE
Please add APK for latest version

### ISSUE THREAD

**Issue by IzzySoft** [AtlantPlatform/atlant-android#1]
Could you please add the latest APK to its corresponding tag here at Github? Thanks!

**Comment by IzzySoft** [comment]
@androidjava3 any chance?

**Comment by egdn** [comment]
@IzzySoft published APK of the current version (v0.6.2) on the [Releases page](https://github.com/AtlantPlatform/atlant-android/releases/latest)

**Comment by IzzySoft** [comment]
Thanks a lot!
